CREATE TABLE movie_medias (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) NOT NULL,
    type TINYINT NOT NULL,
    movie_id INT NOT NULL,
    FOREIGN KEY(movie_id) REFERENCES movies(id),
    PRIMARY KEY(id)
);

INSERT INTO movie_medias 
(name, type, movie_id)
VALUES 
('madame-web-1.jpg', 2, 1),
('madame-web-2.jpg', 0, 1),
('madame-web-3.jpg', 0, 1),
('madame-web-4.jpg', 0, 1),
('madame-web-5.jpg', 0, 1),
('madame-web-6.jpg', 0, 1),
('madame-web-7.jpg', 0, 1),
('madame-web-8.jpg', 0, 1),
('madame-web-9.jpg', 0, 1),
('madame-web-clip-1.mp4', 1, 1),
('madame-web-clip-2.mp4', 1, 1),
('madame-web-trailer.mp4', 3, 1),
('batman-1.jpg', 2, 2),
('batman-2.jpg', 0, 2),
('batman-3.jpg', 0, 2),
('batman-4.jpg', 0, 2),
('batman-5.jpg', 0, 2),
('batman-6.jpg', 0, 2),
('batman-7.jpg', 0, 2),
('batman-8.jpg', 0, 2),
('batman-9.jpg', 0, 2),
('batman-10.jpg', 0, 2),
('batman-clip-1.mp4', 1, 2),
('batman-clip-2.mp4', 1, 2),
('batman-trailer.mp4', 3, 2),
('patch-adams-1.jpg', 0, 3),
('patch-adams-2.jpg', 0, 3),
('patch-adams-3.jpg', 0, 3),
('patch-adams-4.jpg', 0, 3),
('patch-adams-5.jpg', 0, 3),
('patch-adams-6.jpg', 0, 3),
('patch-adams-7.jpg', 0, 3),
('patch-adams-8.jpg', 0, 3),
('patch-adams-9.jpg', 0, 3),
('patch-adams-10.jpg', 2, 3),
('angel-a-1.jpg', 2, 4),
('angel-a-2.jpg', 0, 4),
('angel-a-3.jpg', 0, 4),
('angel-a-4.jpg', 0, 4),
('angel-a-5.jpg', 0, 4),
('angel-a-6.jpg', 0, 4),
('angel-a-7.jpg', 0, 4),
('angel-a-8.jpg', 0, 4),
('angel-a-9.jpg', 0, 4),
('angel-a-10.jpg', 0, 4),
('angel-a-trailer.mp4', 3, 4)